sudo: required
services:
  - docker

before_install:
  - docker build -t harryadel/react-test -f ./client/Dockerfile.dev

script:
  - docker run harryadel/react-test npm test -- --coverage

after_success:
  - docker build -t harryadel/multi-client  ./client
  - docker build -t harryadel/multi-nginx ./nginx
  - docker build -t harryadel/multi-server ./server
  - docker build -t harryadel/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harryadel/multi-client
  - docker push harryadel/multi-nginx
  - docker push harryadel/multi-server
  - docker push harryadel/multi-worker